# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
